[tool.poetry]
name = "messager"
version = "0.1.0"
description = ""
authors = ["Artur Chabowski <a.j.chabowski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
twilio = "^9.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
