export function load() { return {crops : [
    "Almendro",
    "Albaricoque temprano",
    "Albaricoque",
    "Ciruelo",
    "Cítricos",
    "Higuera",
    "Manzano",
    "Melocotón extratemprano",
    "Melocotón temprano",
    "Melocotón media estación",
    "Melocotón tardío",
    "Caqui *",
    "Níspero *",
    "Granado *",
    "Olivo",
    "RDC Olivo",
    "Peral",
    "Uva mesa espaldera 1 año",
    "Uva mesa espaldera 2º año",
    "Uva mesa espaldera adulta",
    "Uva mesa Parral 1º año",
    "Uva mesa Parral 2º año",
    "Uva mesa Parral 3º año",
    "Uva mesa Parral adulto",
    "Viña Vino"
  ]}}